// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa9TADhZWXcOwF8xNvyDD4Pdkhzm6epqI',
    appId: '1:786218857395:web:4d855e48848c44532d11c6',
    messagingSenderId: '786218857395',
    projectId: 'cosecheros',
    authDomain: 'cosecheros.firebaseapp.com',
    storageBucket: 'cosecheros.appspot.com',
    measurementId: 'G-QS2QX108W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC28kboUTFE88PdC3BAv4_UckWA0p1qDo',
    appId: '1:786218857395:android:84c5fe64f580135a2d11c6',
    messagingSenderId: '786218857395',
    projectId: 'cosecheros',
    storageBucket: 'cosecheros.appspot.com',
  );
}
